### ISSUE TITLE
How to reconstruct the trajectory when inference?

### ISSUE THREAD

**Issue by chenjx1005** [InhwanBae/EigenTrajectory#1]
Thanks for your work. 

The method has some anchors of the coefficients. You use the minimal difference between the reconstruction and ground-truth trajectory to choose the right anchor when training. However, during inference, since we don't have the GT trajectory, how to choose the right anchor and do reconstrution?

**Comment by InhwanBae** [comment]
Hi @chenjx1005,

Thank you for showing interest in my paper. In the EigenTrajectory model, the anchor is created once before the training phase, and the network selects a trajectory with a minimal difference to learn how to refine it (because the ground truth is not multimodal and only provides one real path). During testing, all 20 trajectories included in the anchor are refined and evaluated, following standard benchmarks.

I am organizing the code for release, and it will be made public soon. It will probably be easier to understand when you see the code.

**Comment by InhwanBae** [comment]
Hi @chenjx1005, I just released the code. Checking the [`./utils/trainer.py`](https://github.com/InhwanBae/EigenTrajectory/blob/main/utils/trainer.py#L172-L195) will be helpful in understanding the evaluation method.

https://github.com/InhwanBae/EigenTrajectory/blob/a6c8a3bfa84da8cc1db14bf4f7ba47872edbfb2b/utils/trainer.py#L249-L264
